language: c
arch:
    - amd64
    - ppc64le
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
before_install:
  - export OPAMYES=1
  - opam init
  - opam install -q -y ocamlfind base-bytes
  - eval `opam config env`

script: ./bootstrap && ./configure && make && make -C examples test-base
